# Generated by Django 4.1.5 on 2023-01-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='technology',
            new_name='Technology',
        ),
    ]
